config/routes.rb
Rails.application.routes.draw do
  root "sessions#home"

  get '/auth/:provider/callback', to: 'sessions#omniauth'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :notes, only: [:edit, :update, :destroy]

  resources :games do
    resources :owned_games, only: [:new, :create]
    resources :notes, only: [:new, :create]
  end

  resources :owned_games, except: [:index, :show, :new, :create, :edit]

  resources :users, except: [:new, :create] do
    resources :games, only: [:index]

    get '/account', to: 'users#edit'
  end

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :username, :email, presence: true, uniqueness: { case_sensitive: false }

  has_many :owned_games
  has_many :games, through: :owned_games

  has_many :owned_games_platforms
  has_many :games_platforms, through: :owned_games_platforms


  scope :sort_by_username, -> { order(:username) }

  def recently_added_games
    self.owned_games.recently_added.collect do |og|
      Game.find_by(id: og.game_id)
    end
  end

  def owns_game_platform?(g_id, p_id)
    gp = GamesPlatform.find_by(game_id: g_id, platform_id: p_id)
    self.games_platforms.include?(gp)
  end

  def owns_game_by_title?(title)
    self.games.find_by(title: title)
  end

  def owns_game_by_instance?(game)
    self.games.include?(game)
  end

  def owns_game_by_id?(g_id)
    self.games.find_by(id: g_id)
  end

  def add_game_by_game_and_platform(game, platform)
    self.games << game
    add_games_platform_by_game_and_platform(game, platform)
  end

  def add_game_by_games_platform(games_platform)
    self.games << Game.find_by(id: games_platform.game_id)
    self.games_platforms << games_platform
  end

  def add_games_platform_by_game_and_platform(game, platform)
    self.games_platforms << GamesPlatform.find_by_ids(game.id, platform.id)
  end

  def currently_playing
    Game.joins(:owned_games).where('user_id = ? AND status = ?', self.id, "Currently Playing")
  end

  def find_owned_game_by_game_id(g_id)
    self.owned_games.find_by(game_id: g_id)
  end

  def owns_game_on_all_platforms?(game)
    self.games.find_by(id: game.id).which_platforms?(self).size == game.platforms.size
  end

  def delete_from_collection(game)
    self.owned_games.find_by(game_id: game.id).destroy
    ogs = OwnedGamesPlatform.joins(:games_platform).where("user_id = ? AND game_id = ?", self.id, game.id)
    ogs.destroy_all
  end

  def added_game?(game)
    self.id == game.added_by
  end

  def get_avatar_url
    "https://robohash.org/#{self.username}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_if_not_logged_in, except: [:new, :create]
  before_action :redirect_if_logged_in, only: [:new, :create]

  def index
    @users = User.sort_by_username
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to games_path
    else
      render :new
    end
  end

  def edit
    @user = User.find_by(id: params[:user_id])
    redirect_to root_path if !@user || !is_current_user?(@user)
  end

  def update
    @user = User.find_by(id: params[:id])
    @user.update(user_params)

    if @user.save
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def show
    @user = User.find_by(id: params[:id])
    redirect_to root_path if !is_current_user?(@user)
  end

  def destroy
    @user = User.find_by(id: params[:id])
    @user.destroy
    session.clear

    redirect_to root_path
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def display_avatar(user)
    content_tag :div, class: "pa4 tc" do
      tag.image src: user.get_avatar_url, height: 40, alt: "avatar"
    end
  end
end

app/views/users/_form.html.erb
<%= render 'layouts/errors', { object: user } %>

<%= form_for(user, url: path) do |f| %>
  <div class="form-group col-md-6">
    <%= f.label :username, class: "col-form-label" %>
    <%= f.text_field :username, class: "form-control" %>
  </div>
  <div class="form-group col-md-6">
    <%= f.label :email, class: "col-form-label" %>
    <%= f.text_field :email, class: "form-control" %>
  </div>
  <div class="form-group col-md-6">
    <%= f.label :password, class: "col-form-label" %>
    <%= f.password_field :password, class: "form-control" %>
  </div>
  <div class="form-group col-md-6">
    <%= f.label :password_confirmation, class: "col-form-label" %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>

  <%= f.submit class: "#{submit_button_classes} ml-3" %>
<% end %>

app/views/users/_list_group_card.html.erb
<div class="col-auto mt-4">
  <div class="card" style="width: 18rem;">
    <div class="card-header font-weight-bold text-light text-center bg-dark">
     <%= header_text %>
    </div>
    <ul class="list-group list-group-flush">
    <% games.each do |game| %>
        <li class="list-group-item"><%= link_to game.title, game_path(game) %></li>
    <% end %>
    </ul>
  </div>
</div>

app/views/users/edit.html.erb
<%= display_title("Update Account") %>

<%= render 'form', { user: @user, path: user_path(current_user) } %>

<%= form_for(@user, method: 'delete') do |f| %>
  <%= f.submit "Delete Account", data: { confirm: 'Are you sure? This cannot be undone.'}, class: "btn btn-danger mt-4 ml-3" %>
<% end %>

app/views/users/index.html.erb
<%= display_title("Users") %>

<% @users.each do |user| %>
  <article class="mw5 center bg-white br3 pa3 pa4-ns mv3 ba b--black-10">
    <div class="tc">
       <%= display_avatar(user) %>
      <h1 class="f3 mb2"><%= user.username %></h1>
      <h2 class="f5 fw4 gray mt0">owns <%= pluralize(user.games.total_by_title, "game") %></h2>
    </div>
</article>

<% end %>

app/views/users/new.html.erb
<%= display_title("Sign Up") %>

<%= render 'users/form', { user: @user, path: signup_path } %>

app/views/users/show.html.erb
<%= display_title("#{@user.username}'s Home") %>

<div class="row d-flex justify-content-center">
  <% if @user.games.empty? %>
    <h2 class="text-center font-weight-light">You have no games in your collection! :(</h2>
  <% else %>
    <div class="row">
      <%= render partial: 'list_group_card', locals: {games: @user.recently_added_games, header_text: "Recently Added"} %>
      <%= render partial: 'list_group_card', locals: {games: @user.currently_playing.sort_by_title, header_text: "Currently Playing"} %>
    </div>
  <% end %>

</div>