config/routes.rb
Rails.application.routes.draw do
  root "sessions#home"

  get '/auth/:provider/callback', to: 'sessions#omniauth'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :notes, only: [:edit, :update, :destroy]

  resources :games do
    resources :owned_games, only: [:new, :create]
    resources :notes, only: [:new, :create]
  end

  resources :owned_games, except: [:index, :show, :new, :create, :edit]

  resources :users, except: [:new, :create] do
    resources :games, only: [:index]

    get '/account', to: 'users#edit'
  end

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/game.rb
class Game < ApplicationRecord
  validates :title, presence: true, uniqueness: { case_sensitive: false }

  has_many :games_platforms
  has_many :platforms, through: :games_platforms

  has_many :owned_games
  has_many :users, through: :owned_games

  scope :sort_by_title, -> { order("lower(title)") }
  scope :last_added, -> { order(created_at: :desc).limit(1) }
  scope :recently_added, -> { order(created_at: :desc).limit(3).distinct }
  scope :total_by_title, -> { count }

  def is_owned?
    !self.users.empty?
  end

  def is_only_owned_by_user?(user)
    self.users.size == 1 && self.users.find_by(id: user.id)
  end

  def which_platforms?(user)
    user.games_platforms.where(game_id: self.id).joins(:platform).pluck(:name)
  end

  def on_multiple_platforms?
    self.platforms.size > 1
  end

  def get_added_by_username
    user = User.find_by(id: self.added_by)
    user ? user.username : nil
  end

  def self.exists_by_title?(title)
    Game.where("LOWER(title) LIKE ?", title).take
  end
end

app/models/owned_game.rb
class OwnedGame < ApplicationRecord
  belongs_to :user
  belongs_to :game

  has_many :notes

  def self.statuses
    ["Want To Play", "Currently Playing", "Completed"]
  end

  scope :recently_added, -> { order(created_at: :desc).limit(3).distinct }

  # def get_status
  #   self.status.split('_').each { |word| word.capitalize! }.join(' ')
  # end

  def self.remove_blanks_from_array(array)
    array.filter! { |data| !data.blank? }
  end

  def self.get_game_platforms(params)
    remove_blanks_from_array(params[:platform_ids]).collect do |p_id|
      GamesPlatform.find_by_ids(params[:game_id], p_id)
    end
  end

  def self.create_owned_games_from_params(params, user_id)
    # get the game_platform relationship(s) of a game the user wants to add on the platform(s) they selected
    gps = get_game_platforms(params)

    # return early if the user did not choose any platform(s)
    return false if gps.empty?

    # create a relationship between the game and user
    og = OwnedGame.new(
      user_id: user_id,
      game_id: params["game_id"],
      status: params["status"]
    )

    owned_games = []

    if og.save
      # create a relationship between the user and whichever games_platforms they selected
      owned_games = gps.collect do |gp|
      ogs = OwnedGamesPlatform.new(user_id: user_id, games_platform_id: gp.id)
      ogs.save
      end
    end

    # return true/false if all relationships correctly saved to the db or not
    owned_games.all?
  end
end

app/controllers/owned_games_controller.rb
class OwnedGamesController < ApplicationController
  before_action :redirect_if_not_logged_in

  def new
    @game = Game.find_by(id: params[:game_id])

    if !@game
      flash[:message] = "Game does not exist"
      redirect_to games_path
    end

    if current_user.owns_game_by_instance?(@game)
      flash[:message] = "You already own this game"
      redirect_to game_path(@game)
    end
  end

  def create
    # set up relationships between the user and game and user and games_platforms
    # return true/false if successful or not
    success = OwnedGame.create_owned_games_from_params(params[:owned_game], current_user.id)

    if !success
      flash[:message] = "Select at least 1 platform"

      # set the game up for the re-render
      @game = Game.find_by(id: params[:owned_game][:game_id])
      render :new
      return
    end

    redirect_to user_games_path(current_user)
  end

  def update
    @owned_game = OwnedGame.find_by(id: params[:id])
    @game = Game.find_by(id: params[:owned_game][:game_id])

    if @owned_game.game == @game && valid_status?
      @owned_game.update(status: params[:commit])
      @owned_game.save
    else
      flash[:message] = "Invalid Status Type."
    end

    redirect_to game_path(@game)
  end

  def destroy
    @game = Game.find_by(id: params[:id])
    if @game && current_user.owns_game_by_instance?(@game)
      current_user.delete_from_collection(@game)
    end

    redirect_to user_games_path(current_user)
  end

  private
    def owned_game_params
      params.require(:owned_game).permit(:status, :game_id, platform_ids: [])
    end

    def valid_status?
      # valid statuses are "Want To Play", "Currently Playing", "Completed"
      # Checking for validity against a malicious user altering the html
      OwnedGame.statuses.include?(params[:commit])
    end
end

app/views/owned_games/_radio_button.html.erb
<div class="form-check">
  <%= f.radio_button input_name, input_label, class: "form-check-input" %>
  <%= f.label input_label, class: "form-check-label" %>
</div>

app/views/owned_games/index.html.erb
<% if @owned_games.empty? %>
  <h2>You have no games in your library!<h2>
<% else %>
  <ul>
    <% @owned_games.each do |g| %>
      <div>
        <%= link_to g.title, game_path(g) %>
        - <%= g.which_platforms?(current_user).join(' | ') %>
      </div>
      <br>
    <% end %>
  </ul>
<% end %>

app/views/owned_games/new.html.erb
<%= display_title("Add #{@game.title} to Your Collection") %>

<p><%= @game.summary %></p>

<%= form_for(:owned_game, url: game_owned_games_path) do |f| %>
  <%= f.label :platform_ids, "Select Platform(s)" %><br>
  <div class="form-row align-items-center">
    <div class="form-group col-md-6">
      <%= f.collection_select :platform_ids, @game.platforms.sort_by_name, :id, :name, {}, { class: "form-control", multiple: true } %>
    </div>
  </div>

  <%= render 'radio_button', { input_name: :status, input_label: "Want To Play", f: f} %>
  <%= render 'radio_button', { input_name: :status, input_label: "Currently Playing", f: f} %>
  <%= render 'radio_button', { input_name: :status, input_label: "Completed", f: f} %>

  <%= f.hidden_field :game_id, value: @game.id %>

  <div class="row">
    <%= f.submit "Add to Collection", class: submit_button_classes %>
    <%= link_to "Cancel", games_path, class: "btn btn-danger mt-4 ml-2" %>
  </div>
<% end %>