config/routes.rb
Rails.application.routes.draw do
  root "sessions#home"

  get '/auth/:provider/callback', to: 'sessions#omniauth'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :notes, only: [:edit, :update, :destroy]

  resources :games do
    resources :owned_games, only: [:new, :create]
    resources :notes, only: [:new, :create]
  end

  resources :owned_games, except: [:index, :show, :new, :create, :edit]

  resources :users, except: [:new, :create] do
    resources :games, only: [:index]

    get '/account', to: 'users#edit'
  end

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/game.rb
class Game < ApplicationRecord
  validates :title, presence: true, uniqueness: { case_sensitive: false }

  has_many :games_platforms
  has_many :platforms, through: :games_platforms

  has_many :owned_games
  has_many :users, through: :owned_games

  scope :sort_by_title, -> { order("lower(title)") }
  scope :last_added, -> { order(created_at: :desc).limit(1) }
  scope :recently_added, -> { order(created_at: :desc).limit(3).distinct }
  scope :total_by_title, -> { count }

  def is_owned?
    !self.users.empty?
  end

  def is_only_owned_by_user?(user)
    self.users.size == 1 && self.users.find_by(id: user.id)
  end

  def which_platforms?(user)
    user.games_platforms.where(game_id: self.id).joins(:platform).pluck(:name)
  end

  def on_multiple_platforms?
    self.platforms.size > 1
  end

  def get_added_by_username
    user = User.find_by(id: self.added_by)
    user ? user.username : nil
  end

  def self.exists_by_title?(title)
    Game.where("LOWER(title) LIKE ?", title).take
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :redirect_if_not_logged_in

  def index
    if params[:user_id]
      if is_current_user?(User.find_by(id: params[:user_id]))
        @games = current_user.games.sort_by_title
      else
        flash[:message] =  "Access denied."
        redirect_to games_path
      end
    else
      @games = Game.sort_by_title
    end
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    @game.added_by = current_user.id

    if empty_params?(params[:game][:platform_ids])
      @game.errors.add(:platform, "select at least 1")
    end

    if params[:game][:title].blank?
      @game.errors.add(:title, "cannot be blank")
    end

    if Game.exists_by_title?(params[:game][:title])
      if current_user.owns_game_by_instance?(@game)
        @game.errors.add(:game, "already exists in your collection")
      else
        @game.errors.add(:game, "already exists in the database")
      end
    end

    if @game.errors.empty? && @game.save
      redirect_to new_game_owned_game_path(@game)
    else
      render :new
    end
  end

  def show
    @game = Game.find_by(id: params[:id])
    redirect_to games_path if !@game #todo error

    @owned_game = current_user.find_owned_game_by_game_id(@game.id)
    # @notes = owned_game.notes if owned_game
  end

  def edit
    @game = Game.find_by(id: params[:id])
    if !@game || !current_user.added_game?(@game)
      flash[:message] = "Access denied"
      redirect_to game_path(@game)
    end
  end

  def update
    @game = Game.find_by(id: params[:id])
    @game.update(game_params)

    if @game.save
      redirect_to game_path(@game)
    else
      render :edit
    end
  end

  private
    def game_params
      params.require(:game).permit(:title, :summary, :image, platform_ids: [])
    end

end

app/helpers/games_helper.rb
module GamesHelper
  def owned_platforms_as_string(user, game)
    game.which_platforms?(user).join(' | ')
  end
end

app/views/games/_form.html.erb
<%= render 'layouts/errors', { object: @game } %>

<%= form_for(@game) do |f| %>

  <% if @game.is_only_owned_by_user?(current_user) || !@game.is_owned? %>
    <div class="form-row align-items-center">
      <div class="form-group col-md-6">
        <%= f.label :title, class: "col-form-label" %>
        <%= f.text_field :title, class: "form-control" %>
      </div>
    </div>

    <div class="form-row align-items-center">
      <div class="form-group col-md-6">
        <%= f.label :platform_ids, "Select Platform(s)", class: "col-form-label" %>
        <%= f.collection_select :platform_ids, Platform.all.sort_by_name, :id, :name, {}, {class: "form-control", multiple: true } %>
      </div>
    </div>
  <% end %>

  <div class="form-row align-items-center">
    <div class="form-group col-md-6">
      <%= f.label :summary, class: "col-form-label" %>
      <%= f.text_area :summary, class: "form-control" %>
    </div>
  </div>

  <%= f.submit class: submit_button_classes %>
<% end %>

app/views/games/_game_platforms.html.erb
<% game.platforms.each do |p| %>
  <span class=<%= current_user.owns_game_platform?(game.id, p.id) ? "text-darker" : "font-weight-light text-muted"  %>>
    <%= p.name %>
  </span>
<% end %>

app/views/games/edit.html.erb
<%= display_title("Edit #{@game.title}") %>

<%= render 'form' %>

app/views/games/index.html.erb
<%= display_title("Games") %>

<% if !@games %>
  <h2 class="display-2 text-center">Games will show up once users start adding them!</h2>
<% else %>
  <ul class="list-group">
    <% @games.each do |game| %>
      <li class="list-group-item d-flex  align-items-center">
        <div class="col-4">
          <%= link_to game.title, game_path(game), class: "text-dark font-weight-bolder" %>
        </div>
        <div class="col-4">
          <h6><%= render 'game_platforms', { game: game } %></h6>
        </div>
        <div class="col-4 text-right">
          <% if current_user.owns_game_by_id?(game.id) %>
            <span class="badge badge-success badge-pill"><%= current_user.find_owned_game_by_game_id(game.id).status %></span>
          <% else %>
            <%= link_to "Add Game to Collection", new_game_owned_game_path(game) %>
          <% end %>
        </div>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/games/new.html.erb
<%= display_title("Create Game") %>

<p>If you can't find the game you're looking for, you can add it to the database here. Once it's created you can add it to your collection</p>

<%= render 'form' %>

app/views/games/show.html.erb
<div class="row d.flex justify-content-end mt-3 mr-1">
  <% if !@owned_game %>
    <div class="col-auto justify-self-center">
      <%= link_to "Add to Collection", new_game_owned_game_path(@game.id), class: "btn btn-outline-secondary btn-sm" %>
    </div>
  <% end %>

  <span class="text-muted font-weight-light">
    <% if current_user.added_game?(@game) %>
      <%= link_to "Edit Game Info", edit_game_path(@game), class: "btn btn-outline-primary btn-sm" %>
    <% elsif @game.added_by %>
      <%= "[Added by #{@game.get_added_by_username ? @game.get_added_by_username : 'Deleted User' }]" %>
    <% end %>
  </span>
</div>

<% if @owned_game && @owned_game.status %>
  <div class="row m-4 d.flex justify-content-center">
    <div class="col-auto">
      <h4><span class="badge badge-pill badge-success">Status: <%= @owned_game.status %></span></h4>
    </div>
  </div>
<% end %>

<h1 class="display-1 text-center"><%= @game.title %></h1>

<h6 class="text-center">
  <%= render 'game_platforms', { game: @game } %>
</h6>

<div class="my-4">
  <h3 class="display-6">Summary:</h3>
  <p><%= @game.summary %></p>
</div>

<% if @owned_game %>
  <hr class="my-4">

  <div class="row d-flex justify-content-end align-items-center mb-4">
    <%= link_to "Add Note", new_game_note_path(@game), class: "btn btn-outline-secondary" %>

    <div class="btn-group mx-3" role="group" aria-label="Basic example">
      <% OwnedGame.statuses.each.with_index(1) do |status, index| %>

        <% if @owned_game.status == status %>
            <button disabled class="btn btn-success" id="status-#{index}"><%= status %></button>
          <% else %>
            <%= form_for(@owned_game) do |f| %>
              <%= f.hidden_field :game_id, value: @game.id %>
              <%= f.submit status, class: "btn btn-secondary", id:"status-#{index}" %>
            <% end %>

          <% end %>
        <% end %>
      </div>
    <%= form_for(@owned_game, url: owned_game_path(@game), method: 'delete') do |f| %>
      <%= f.submit "Delete Game From Collection", data: { confirm: 'Are you Sure? You will lose all your notes'}, class: "btn btn-danger" %>
    <% end %>
  </div>

  <h3 class="display-4 text-center">Notes/Objectives</h3>

  <% @owned_game.notes.sort_newest_first.each do |note| %>
    <div class="card my-4">
      <div class="card-body">
        <div class="row">
          <div class="col-sm-9">
            <h5 class="card-title <%='strikethrough' if note.completed %>" >
              <%= note.title %>
            </h5>
          </div>
          <div class="col-sm-3">
            <h6 class="card-subtitle mb-2 text-muted"><%= human_readable_datetime(note.created_at) %></h6>
          </div>
        </div>
        <p class="card-text"><%= note.content %></p>
        <div class="row justify-content-end">
          <div class="d-inline-flex col-auto mr-3">
            <%= link_to "Edit Note", edit_note_path(note), class: "btn btn-outline-primary btn-sm mr-2" %>


            <%= button_to "Delete Note", note_path(note), method: 'delete', data: { confirm: "Are you sure? This cannot be undone."}, class: "btn btn-outline-danger btn-sm" %>
          </div>
        </div>
      </div>
    </div>
    <div>
  <% end %>

<% end %>