config/routes.rb
Rails.application.routes.draw do
  root "sessions#home"

  get '/auth/:provider/callback', to: 'sessions#omniauth'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :notes, only: [:edit, :update, :destroy]

  resources :games do
    resources :owned_games, only: [:new, :create]
    resources :notes, only: [:new, :create]
  end

  resources :owned_games, except: [:index, :show, :new, :create, :edit]

  resources :users, except: [:new, :create] do
    resources :games, only: [:index]

    get '/account', to: 'users#edit'
  end

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this article from being saved:</h2>

    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GametrackerRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: black;">
      <a class="navbar-brand" href="/">GameTracker</a>
      <% if logged_in? %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      <% end %>

      <div class="navbar-nav collapse navbar-collapse" id="navbarNavDropdown">
        <% if logged_in? %>
          <%= link_to "Games", games_path, class: "nav-item nav-link" %>
          <%= link_to "Add New Game", new_game_path, class: "nav-item nav-link" %>
          <%= link_to "#{current_user.username} Home", user_path(current_user), class: "nav-item nav-link" %>
          <%= link_to "My Collection", user_games_path(current_user), class: "nav-item nav-link" %>
          <%= link_to "Account", user_account_path(current_user), class: "nav-item nav-link" %>
          <%= link_to "Log Out", logout_path, method: 'delete', class: "nav-item nav-link" %>
        <% end %>
      </div>
    </nav>
    <%= flash[:message] if flash[:message] %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>